name: Update README with blog posts

on:
  schedule:
    - cron: '0 * * * *' # runs every hour
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Fetch and update blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://jonathanprogram2.hashnode.dev/rss.xml"
